### ISSUE TITLE
Error after update to Fody 3.0.0 and Caseless 1.8.0

### ISSUE THREAD

**Issue by FutureTD** [Fody/Caseless#13]
Updated all nuget packages to fody 3.0.0 updated caseless to 1.8.0 and getting this error:

Fody: The weaver assembly 'Caseless.Fody, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.

**Comment by SimonCropp** [comment]
a smoke test for me works. can u upload a small sln that reproduces the issue

**Comment by FutureTD** [comment]
Fixed the error. Just deleted the old version folder that was cached and reinstalled.

**Comment by SimonCropp** [comment]
Good to hear
