### ISSUE TITLE
Support for .NET 5

### ISSUE THREAD

**Issue by FutureTD** [Fody/Caseless#280]
Could this be updated to work with .NET 5? 

When I attempt to install from nuget it is asking for a ton of dependencies within a .NET 5 project.

**Comment by SimonCropp** [comment]
did you read the issue template?

**Comment by FutureTD** [comment]
I re-read the template and have became a patron for fody

**Comment by SimonCropp** [comment]
this works for me on net 5. can u share a repro?

**Comment by FutureTD** [comment]
When I went to install the nuget package even on a fresh project I get this:

![image](https://user-images.githubusercontent.com/18328217/109815659-e1319f00-7bfd-11eb-8293-955722ba1038.png)

I assumed that all those packages I had to redistribute in my app. But I assume they are all included in .NET 5. If so It doesn't seem to be an issue.
